Repository adventistchurch/alps-wordpress, pull requests merged in 2018-12, with the labels that each got.

#263 Pagination for category pages
  assets/styles/main.scss
  dist/scripts/customizer.js.map
  dist/scripts/main.js.map
  dist/styles/main.css
  dist/styles/main.css.map
  functions.php
  views/index.blade.php
Labels: ALPS v.3, bug

#269 #267 Made Gutenberg required only on WP 5.0 and lower.
  functions.php
Labels: ALPS v.3, bug

#271 Fixing the Site Branding statement.
  piklist/parts/settings/settings-theme.php
Labels: ALPS v.3

#272 V3 #252: Adding _e() to translatable strings.
  LICENSE.md
  README.md
  app/controllers/app.php
  app/filters.php
  app/setup.php
  functions.php
  lang/alps.pot
  lang/es.mo
  lang/es.po
  piklist/parts/widgets/author-box.php
  piklist/parts/widgets/post-feed.php
  piklist/parts/widgets/text-with-link.php
  style.css
  views/404.blade.php
  views/index.blade.php
  views/patterns/00-atoms/icons/icon-arrow-bracket-left.blade.php
  views/patterns/00-atoms/icons/icon-arrow-bracket-right.blade.php
  views/patterns/00-atoms/icons/icon-arrow-long-left.blade.php
  views/patterns/00-atoms/icons/icon-arrow-long-right.blade.php
  views/patterns/00-atoms/icons/icon-arrow-short-left.blade.php
  views/patterns/00-atoms/icons/icon-arrow-short-right.blade.php
  views/patterns/00-atoms/icons/icon-close.blade.php
  views/patterns/00-atoms/icons/icon-contact.blade.php
  views/patterns/00-atoms/icons/icon-dots.blade.php
  views/patterns/00-atoms/icons/icon-find-a-church.blade.php
  views/patterns/00-atoms/icons/icon-language.blade.php
  views/patterns/00-atoms/icons/icon-legal.blade.php
  views/patterns/00-atoms/icons/icon-logo-dark.blade.php
  views/patterns/00-atoms/icons/icon-menu.blade.php
  views/patterns/00-atoms/icons/icon-plus.blade.php
  views/patterns/00-atoms/icons/icon-press.blade.php
  views/patterns/00-atoms/icons/icon-search.blade.php
  views/patterns/00-atoms/icons/icon-settings.blade.php
  views/patterns/00-atoms/icons/icon-share.blade.php
  views/patterns/00-atoms/icons/icon-sitemap.blade.php
  views/patterns/00-atoms/logos/alps-icon-logo-round.blade.php
  views/patterns/00-atoms/logos/alps-icon-logo.blade.php
  views/patterns/01-molecules/components/share-tools.blade.php
  views/patterns/01-molecules/forms/search.blade.php
  views/patterns/01-molecules/navigation/secondary-navigation.blade.php
  views/patterns/02-organisms/asides/related-stories.blade.php
  views/patterns/02-organisms/content/content-search.blade.php
  views/patterns/02-organisms/sections/article-footer.blade.php
  views/patterns/02-organisms/sections/comments.blade.php
  views/patterns/02-organisms/sections/page-header.blade.php
  views/patterns/02-organisms/sections/related-pages.blade.php
  views/template-posts.blade.php
Labels: ALPS v.3, i18n
